@startuml shopping_mall
entity Cart{
    *id : int <<identity>>
    *username: string
    *items:CartItem
    *totalPrice:decimal
}
entity CartItem{
    *id: int <<identity>>
    *quantity: int
    *color: string
    *price: decimal
    *product_id: int
    *product:Product
}
entity Category {
    *id :int <<identity>>
    *name : string
    *description :string
    *image_name: string
}
entity Contact{
    *id:int <<identity>>
    *name: string
    *phone: string
    *email: string
    *message: string

}
entity Order{
    *id:int
    *user_name: string
    *total_price:decimal
    -- billing 
    *first_name:string
    *last_name:string
    *email_address:string
    *address_line:string
    *country:string
    *state:string
    *zipcode:string
    --payment
    *card_name:string
    *card_number:string
    *expiration:string
    *payment_method:PaymentMethod(1,2,3)

}
entity Product{
    *id:int <<identity>>
    *name:string
    *summary:string
    *description:string
    *price:decimal
    *category_id:int
    *category:Category
}
Cart --o{ CartItem
Product -- CartItem
Product -- Category
@enduml